### ISSUE TITLE
Unable to connect to Dask Scheduler

### ISSUE THREAD

**Issue by duncanwp** [awslabs/amazon-asdi#20]
Thanks for this really useful resource! I'm struggling to make my Sagemaker notebook connect to the ECS cluster though. The `Client` instantiation fails with:

```
lient = Client('Dask-Scheduler.local-dask:8786')
client
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-f0505c27a7d1> in <module>
----> 1 client = Client('Dask-Scheduler.local-dask:8786')
      2 client

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, serializers, deserializers, extensions, direct_to_workers, connection_limit, **kwargs)
    742             ext(self)
    743 
--> 744         self.start(timeout=timeout)
    745         Client._instances.add(self)
    746 

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in start(self, **kwargs)
    946             self._started = asyncio.ensure_future(self._start(**kwargs))
    947         else:
--> 948             sync(self.loop, self._start, **kwargs)
    949 
    950     def __await__(self):

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in _start(self, timeout, **kwargs)
   1043 
   1044         try:
-> 1045             await self._ensure_connected(timeout=timeout)
   1046         except OSError:
   1047             await self._close()

~/anaconda3/envs/daskpy3/lib/python3.7/site-packages/distributed/client.py in _ensure_connected(self, timeout)
   1124         else:
   1125             msg = await comm.read()
-> 1126         assert len(msg) == 1
   1127         assert msg[0]["op"] == "stream-start"
   1128 

AssertionError: 
```

I've looked in the CloudWatch logs and can see errors like this in the Scheduler:

```
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f3f1e61b290>, <Task finished coro=<BaseTCPListener._handle_stream() done, defined at /opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py:459> exception=ValueError('Your Dask versions may not be in sync. Please ensure that you have the same version of dask and distributed on your client, scheduler, and worker machines')>)
--
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/distributed/comm/core.py", line 140, in handshake_configuration
local["pickle-protocol"], remote["pickle-protocol"]
KeyError: 'pickle-protocol'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
ret = callback()
File "/opt/conda/lib/python3.7/site-packages/tornado/tcpserver.py", line 331, in <lambda>
gen.convert_yielded(future), lambda f: f.result()
File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 471, in _handle_stream
await self.on_connection(comm)
File "/opt/conda/lib/python3.7/site-packages/distributed/comm/core.py", line 238, in on_connection
comm.local_info, comm.remote_info
File "/opt/conda/lib/python3.7/site-packages/distributed/comm/core.py", line 148, in handshake_configuration
) from e
ValueError: Your Dask versions may not be in sync. Please ensure that you have the same version of dask and distributed on your client, scheduler, and worker machines
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.0.18.82:8786 remote=tcp://10.0.3.170:49034>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.0.18.82:8786 remote=tcp://10.0.3.170:49036>
```
How should I remedy this?

**Comment by duncanwp** [comment]
Closed per #21
